In [209]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.0+cu121


## Introduction to Tensors

### Creating Tensors

In [210]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [211]:
scaler.ndim

0

In [212]:
# Get tensor back as python int
scaler.item()


7

In [213]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [214]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [215]:
# Matrix
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [216]:
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [217]:
MATRIX[1]

tensor([ 9, 10])

In [218]:
# Tensor
TENSOR = torch.tensor([[
          [1,2,3],
          [4,5,6],
          [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [219]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


In [220]:
TENSOR[0, 1]

tensor([4, 5, 6])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.



In [221]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4068, 0.0602, 0.7752, 0.8092],
        [0.0949, 0.6401, 0.0189, 0.3340],
        [0.6411, 0.9428, 0.7822, 0.7043]])

In [222]:
random_tensor.ndim

2

In [223]:
# Create a random tensor with similar shape
random_image_tensor = torch.rand(size=(224, 224, 3)) # (h x w x color channels)

In [224]:
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [225]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [226]:
# Create tensor with all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [227]:
ones.dtype

torch.float32

In [228]:
random_tensor.dtype

torch.float32

### Range of Tensors and tensors-like

In [229]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=10, step=1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [230]:
# Creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [231]:
# Float (32) tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9,0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9., 0.])

In [232]:
float_32_tensor.dtype

torch.float32

In [233]:
float_16_tensor = float_32_tensor.type(torch.half) # torch.float16
float_16_tensor.dtype

torch.float16

In [234]:
float_tensor_result = float_16_tensor * float_32_tensor

float_tensor_result.dtype

torch.float32

### Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor you can use `tensor.dtype`

2. Tensors not right shape - to get shape of a tensor, use `tensor.shape`

3. Tensors not on the right device - to get device from a tensor, you can use `tensor.device`

In [235]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8708, 0.0428, 0.9441, 0.1703],
        [0.8086, 0.7652, 0.7517, 0.0108],
        [0.3369, 0.6062, 0.8815, 0.7432]])

In [236]:
# Find out details about some tensor
print(some_tensor)

print(f"Datatype of tensor is {some_tensor.dtype}")
print(f"Size of tensor is {some_tensor.shape}")
print(f"Device the tensor is running on is {some_tensor.device}")


tensor([[0.8708, 0.0428, 0.9441, 0.1703],
        [0.8086, 0.7652, 0.7517, 0.0108],
        [0.3369, 0.6062, 0.8815, 0.7432]])
Datatype of tensor is torch.float32
Size of tensor is torch.Size([3, 4])
Device the tensor is running on is cpu


### Manipulating Tensors (tensor ops)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [237]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])

print(tensor + 10)
print(tensor - 1)

print(tensor / 2)


tensor([11, 12, 13])
tensor([0, 1, 2])
tensor([0.5000, 1.0000, 1.5000])


In [238]:
%%time
print(tensor * 10)

tensor([10, 20, 30])
CPU times: user 435 µs, sys: 33 µs, total: 468 µs
Wall time: 453 µs


In [239]:
# Built-in PyTorch functions
%time
torch.mul(tensor, 10)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.44 µs


tensor([10, 20, 30])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)



In [240]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [241]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [242]:
%%time
value =0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

value

CPU times: user 1.03 ms, sys: 0 ns, total: 1.03 ms
Wall time: 967 µs


tensor(14)

In [243]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 68 µs, sys: 5 µs, total: 73 µs
Wall time: 76.3 µs


tensor(14)

## Dealing with *shape errors*

In [244]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

In [245]:
## torch.mm(tensor_A, tensor_B)

# Will not work as shape is (3, 2) and (3, 2)

# torch.mm is same as torch.matmul

To fix our tensor shape issues, we can manipulate the shape of one of our tensor using **transpose**.

A **transpose** switches the axes or dimenstions of a given tensor

In [246]:
tensor_B.shape

torch.Size([3, 2])

In [247]:
tensor_B.T.shape

torch.Size([2, 3])

In [248]:
tensor_B.T @ tensor_B

tensor([[194, 266],
        [266, 365]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [249]:
X = torch.arange(0, 100, step=10)
X

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [250]:
# Find the min
torch.min(X), torch.max(X)

(tensor(0), tensor(90))

In [251]:
# Find the mean (Input must be floating point or complex)
torch.mean(X.type(torch.float32))

tensor(45.)

In [252]:
# Find the sum
torch.sum(X), X.sum()

(tensor(450), tensor(450))

In [253]:
# Find pos. of max and min
torch.argmax(X), torch.argmin(X)

(tensor(9), tensor(0))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine mulitple tensors on top of each other (VStack) and side by side (HStack)
* Squeeze - removes all `1` dimenstions from a tensor
* UnSqueeze - adds a `1` dimenstion to a target tensor
* Premute - Returns a view of the input with dimenstions permuted (swapped) in a certain way

In [254]:
# Let's create a tensor
X = torch.arange(1., 11.)
X, X.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [255]:
X_reshaped = X.reshape(10, 1)
X_reshaped, X_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [256]:
X_reshaped = X.reshape(5, 2)
X_reshaped, X_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [257]:
# Change the view
Z = X.view(2, 5)
Z, Z.shape

# Changing Z changes X becuase a view of a tensor shares the same memory as the original tensor

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [258]:
# Stacking on top
X_stack = torch.stack([X, X, X, X], dim=0)
X_stack

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [259]:
# Stacking side by side
X_stack = torch.stack([X, X, X, X], dim=1)
X_stack

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [260]:
h_stack = torch.hstack((X, X, X, X))
h_stack

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.,  1.,  2.,  3.,  4.,
         5.,  6.,  7.,  8.,  9., 10.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
         9., 10.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [261]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y = torch.tensor([[7, 8, 9], [10, 11, 12]])

result = torch.hstack((x, y))
print(result)


tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])


In [262]:
# torch.squeeze()
X_reshaped.shape

torch.Size([5, 2])

In [263]:
X_reshaped.squeeze()

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [264]:
X_reshaped.squeeze().shape

torch.Size([5, 2])

In [265]:
tensor = torch.rand(size=(1, 1, 4))
tensor, tensor.shape

(tensor([[[0.0502, 0.6107, 0.1593, 0.8314]]]), torch.Size([1, 1, 4]))

In [266]:
# SQUEEZED
tensor_squeezed = tensor.squeeze()
tensor_squeezed, tensor_squeezed.shape

(tensor([0.0502, 0.6107, 0.1593, 0.8314]), torch.Size([4]))

In [267]:
# UNSQUEEZED
tensor_unsqueezed = tensor.unsqueeze(dim=0)
tensor_unsqueezed, tensor_unsqueezed.shape

(tensor([[[[0.0502, 0.6107, 0.1593, 0.8314]]]]), torch.Size([1, 1, 1, 4]))

## Indexing

In [268]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [269]:
# Let's index our tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [270]:
# Let's index on the middle bracket
print(x[0][1])
print(x[0, 1])

# SAME THING

tensor([4, 5, 6])
tensor([4, 5, 6])


In [271]:
# One single element
print(x[0][0][0]) # first element

tensor(1)


In [272]:
# middle element (single)
x[0][1][1]

tensor(5)

In [273]:
# You can also use ":" to sleect "all" of a target dimenstion
x[:, 0]



tensor([[1, 2, 3]])

In [274]:
# Get all values of 0th and 1st dimentions but only 1 index of 2nd dimenstion
x[:, :, 1]

tensor([[2, 5, 8]])

In [275]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [276]:
# get 9
x[:, 2, 2]

tensor([9])

## PyTorch tensors & Numpy

In [277]:
# Converting a NumPy array to PyTorch Tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [278]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [279]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [281]:
# Tensor to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [282]:
tensor.dtype, numpy_tensor.dtype

(torch.float32, dtype('float32'))

## Reproducibilty (trying to take random out of random)

In short how a neural network learns:

`Starts with random numbers -> tensor ops -> update random numbers to try and make them of the data -> again -> again -> again ...`


To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

In [283]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)


tensor([[0.4746, 0.0181, 0.2105, 0.7843],
        [0.0091, 0.1547, 0.4648, 0.6210],
        [0.7137, 0.2579, 0.5067, 0.4133]])
tensor([[0.8094, 0.8097, 0.6043, 0.8268],
        [0.0523, 0.7807, 0.3164, 0.7413],
        [0.8640, 0.7383, 0.3846, 0.9721]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [295]:
# Let's make some random but reprodcible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
